#!/usr/bin/env bash
set -euo pipefail

echo "==> Setting up ENB lighting for Skyrim Special Edition (Bazzite / Linux)"
echo
echo "This step is entirely manual — ENB binaries, the weather mod, and the"
echo "preset must all be downloaded by hand. This script just prints the"
echo "steps in order. Run step 31 (skyrim-modding) first if you haven't already."
echo

GAME_DIR="$HOME/.local/share/Steam/steamapps/common/Skyrim Special Edition"

echo "============================================================"
echo " MANUAL STEPS REQUIRED"
echo "============================================================"
echo
echo "--- STEP A: Install ENB binaries ---"
echo "1. Go to: http://enbdev.com/download_mod_tesskyrimse.html"
echo "2. Download the latest ENBSeries version for TES Skyrim SE"
echo "3. Extract ONLY d3d11.dll and d3dcompiler_46e.dll from the archive's"
echo "   WrapperVersion folder directly into:"
echo "   $GAME_DIR/"
echo "   (do NOT route these through LMO — they must sit in the game root,"
echo "   same as the SKSE64 files from step 31)"
echo
echo "--- STEP B: Install Address Library for SKSE Plugins ---"
echo "This is easy to skip since nothing complains about it until you've"
echo "added enough SKSE-plugin mods (Engine Fixes, ENB Helper SE, Moons and"
echo "Stars, etc.) — one of them will hard-fail on launch citing a missing"
echo "or outdated Address Library otherwise. Grab it now to avoid that:"
echo "  nexusmods.com/skyrimspecialedition/mods/32444"
echo "  Download the 'All in one (all game versions)' file — covers both"
echo "  AE and pre-AE builds — then drag into LMO, Deploy to Data, Deploy."
echo
echo "--- STEP C: Install the weather mod and Rudy ENB's required mods via LMO ---"
echo "Download each of the following (manual download from nexusmods.com),"
echo "then drag into LMO, right-click → Deployers → Data, then Deploy."
echo "The Rudy ENB SE preset's own readme (bundled in its archive, not just"
echo "the Nexus page description) lists ALL of these as mandatory, not"
echo "optional — it explicitly says skipping any of them means the preset"
echo "'can be thrown out the window'."
echo
echo "  1. Cathedral Weathers and Seasons (the base weather mod)"
echo "     nexusmods.com/skyrimspecialedition/mods/24791"
echo
echo "  2. Enhanced Volumetric Lighting and Shadows (EVLaS)"
echo "     nexusmods.com/skyrimspecialedition/mods/63725"
echo "     Also grab the 'Skyrim Underside' file from the same page's Files"
echo "     tab — required unless you're using DynDOLOD 3.0+ (we aren't)"
echo
echo "  3. Moons and Stars - Sky Overhaul SKSE"
echo "     nexusmods.com/skyrimspecialedition/mods/73336"
echo
echo "  4. Particle Patch for ENB"
echo "     nexusmods.com/skyrimspecialedition/mods/65720"
echo "     FOMOD: select 'Remove Fake Glow' and 'Fake Light Glow' (both"
echo "     needed so ENB's own lighting replaces the vanilla fake-glow"
echo "     sprites); 'custom textures' is cosmetic, optional either way"
echo
echo "  5. Embers XD"
echo "     nexusmods.com/skyrimspecialedition/mods/37085"
echo "     (choose the Orange flames, Optimized version with Disabled Red"
echo "     Glow and Reduced Yellow Glow file — that's what Rudy ENB expects)"
echo "     Compatibility patches: only select ones matching mods you"
echo "     actually have installed (e.g. 'JK's' since JK's Skyrim is in the"
echo "     base mod list) — skip patches for mods you don't own"
echo
echo "  6. ENB Helper SE"
echo "     nexusmods.com/skyrimspecialedition/mods/23174"
echo
echo "  7. SSE Engine Fixes (skse64 plugin)"
echo "     nexusmods.com/skyrimspecialedition/mods/17230"
echo "     Get the MAIN plugin file here, through LMO. It also ships a"
echo "     separate 'SKSE64 Preloader' file — do NOT put that through LMO,"
echo "     see Step D below."
echo
echo "  8. Window Shadows RT"
echo "     nexusmods.com/skyrimspecialedition/mods/37831"
echo "     This is the lightweight pick for Rudy ENB's required 'exterior"
echo "     lighting' choice (the alternative, full ELFX + ELFX Fixes, is a"
echo "     much heavier interior relighting overhaul with more compat"
echo "     patches to juggle — Window Shadows RT satisfies the requirement"
echo "     with far less risk of conflicts against JK's Skyrim etc.)"
echo "     After deploying, LMO's LOOT-based Plugins deployer should"
echo "     auto-sort its plugin near the end of load order; spot check it."
echo
echo "  9. Obsidian Mountain Fogs"
echo "     nexusmods.com/skyrimspecialedition/mods/13539"
echo
echo "  10. Water for ENB (Shades of Skyrim)"
echo "      nexusmods.com/skyrimspecialedition/mods/37061"
echo "      GOTCHA: this archive contains a duplicate waterfall mesh file"
echo "      differing only by letter case (FXWaterfallThin2048x128_m.nif"
echo "      vs. the lowercase variant), which are NOT identical files (a"
echo "      stale leftover from the author, not two variant options)."
echo "      LMO's Case Matching Deployer will fail to deploy with a"
echo "      'target already exists' rename error until you delete the"
echo "      uppercase one from the mod's staging folder, e.g.:"
echo "        rm \"\$HOME/LIMO/Skyrim/<mod-id>/meshes/effects/FXWaterfallThin2048x128_m.nif\""
echo "      (find <mod-id> by checking which numbered staging folder holds"
echo "      'Water for ENB' in lmm_mods.json), then redeploy."
echo
echo "  11. Bright Waterfall Fix for ENB"
echo "      nexusmods.com/skyrimspecialedition/mods/37956"
echo
echo "  12. Less Distracting Blowing Snow Effects for ENB Particle Patch"
echo "      nexusmods.com/skyrimspecialedition/mods/36198"
echo
echo "  13. Vanilla Complex Grasses for ENB"
echo "      nexusmods.com/skyrimspecialedition/mods/68640"
echo
echo "  Rough load-order note from the preset readme: Embers XD before"
echo "  Water for ENB, Water for ENB before Obsidian Mountain Fogs and"
echo "  Bright Waterfall Fix."
echo
echo "--- STEP D: Install the SSE Engine Fixes preloader ---"
echo "The main Engine Fixes plugin (Step C.7) silently refuses to activate"
echo "without a separate preloader DLL — the game will launch, but SKSE's"
echo "log shows 'plugin did not preload, please install the preloader' and"
echo "you may see a version-mismatch style error dialog on launch."
echo "1. On the same mod page (nexusmods.com/skyrimspecialedition/mods/17230),"
echo "   download the 'SKSE64 Preloader' file separately"
echo "2. Extract ONLY d3dx9_42.dll from it directly into:"
echo "   $GAME_DIR/"
echo "   (game root, NOT through LMO — same reasoning as the ENB binaries)"
echo
echo "--- STEP E: Install the Rudy ENB SE preset ---"
echo "1. Go to: nexusmods.com/skyrimspecialedition/mods/39113"
echo "   (Rudy ENB SE for Cathedral Weathers)"
echo "2. Download the main preset file. Its archive contains alternate"
echo "   folders for each exterior-lighting choice — extract only the"
echo "   'Cathedral Weathers WINDOW SHADOWS RT' variant's"
echo "   'Normal Game/[ Skyrim SE folder ]' contents (enbseries.ini,"
echo "   enblocal.ini, enbseries/ shaders) directly into:"
echo "   $GAME_DIR/"
echo "   (game root, not through LMO, same reasoning as Step A)"
echo "3. Also download the 'Rudy ENB Cathedral Weathers ADDONS and REQUiRED"
echo "   Files' FOMOD from the same mod's Files tab — this one DOES go"
echo "   through LMO (it overwrites Cathedral Weathers.ini in the Data"
echo "   folder), so drag it into LMO, Deploy to Data, then Deploy."
echo "   FOMOD choices: select the 'Night Eye Version' option under"
echo "   Options (required for Rudy's night-vision effect to work), plus"
echo "   Bright Hawks and Birds Fix, Night sky textures, Snowflakes"
echo "   texture, and Vanilla clouds 4k (matches Skyrim 202X's resolution)."
echo "   Skip 'Wonders of Weather fix' and 'ELFX fix' — both are patches"
echo "   for mods/choices this setup doesn't use."
echo "4. This preset's bundled enblocal.ini already uses Shift+Enter"
echo "   (KeyCombination=16, KeyEditor=13) for the in-game editor, unlike"
echo "   NAC X's FO4 preset — no hotkey fix needed here."
echo
echo "--- STEP F: Configure ENB for Proton/DXVK, then set Linux compatibility flags ---"
echo "1. ENB's default proxy chaining relies on Windows-style path resolution"
echo "   to find the 'real' d3d11.dll, which doesn't reliably work under Wine/"
echo "   Proton. Give it an explicit target instead:"
echo "     PFX=\"\$HOME/.local/share/Steam/steamapps/compatdata/489830/pfx\""
echo "     cp \"\$PFX/drive_c/windows/system32/d3d11.dll\" \"$GAME_DIR/dxvk.dll\""
echo "     sed -i 's/^EnableProxyLibrary=.*/EnableProxyLibrary=true/; s/^InitProxyFunctions=.*/InitProxyFunctions=true/; s/^ProxyLibrary=.*/ProxyLibrary=dxvk.dll/' \"$GAME_DIR/enblocal.ini\""
echo "2. enblocal.ini also has a [GLOBAL] LinuxVersion flag (off by default in"
echo "   every preset) plus a ShaderCache flag under [PERFORMANCE] — both are"
echo "   documented Linux-specific settings worth enabling regardless:"
echo "     sed -i 's/^LinuxVersion=.*/LinuxVersion=true/; s/^ShaderCache=.*/ShaderCache=true/' \"$GAME_DIR/enblocal.ini\""
echo
echo "--- STEP G: Use GE-Proton9-27, NOT GE-Proton Latest ---"
echo "GE-Proton 'Latest' bundles a continuously updated DXVK, and on this"
echo "setup its current version broke ENB's shader effects entirely:"
echo "enbseries.ini's UseEffect=true produced a black screen with only"
echo "ambient audio (wind) during the Helgen intro — engine kept running"
echo "(FPS counter updating, meshes loading per EngineFixes.log) but nothing"
echo "rendered. Neither the Step F proxy/Linux settings, disabling only"
echo "EnableSkylighting/EnableDirectionalSkyLighting, nor toggling UseEffect"
echo "on live in-game (which instead caused a hard freeze) fixed it — this"
echo "matched long-documented ENB+DXVK/Vulkan reports for Skyrim SE (see e.g."
echo "doitsujin/dxvk issues #865, #2033) that read like an unresolved gap."
echo
echo "It wasn't unresolved — it was specifically a GE-Proton 'Latest' DXVK"
echo "regression. Installing the OLDER 'GE-Proton9-27' build via ProtonPlus"
echo "and switching Skyrim Special Edition to it (Steam → Properties →"
echo "Compatibility) fixed ENB's shader effects completely, no ini changes"
echo "needed beyond Step F. This is a per-GAME Steam setting, so switching to"
echo "9-27 for Skyrim doesn't affect Fallout 4 or anything else."
echo
echo "GOTCHA: switching Proton versions re-syncs the prefix's bundled"
echo "system32/d3d11.dll (Wine/Proton's own DXVK) to match whichever build"
echo "is now selected — so the dxvk.dll proxy copy from Step F goes stale"
echo "the moment you change Proton version, and ENB will crash (loader"
echo "opens, a window flashes, then closes) until you refresh it:"
echo "  PFX=\"\$HOME/.local/share/Steam/steamapps/compatdata/489830/pfx\""
echo "  cp \"\$PFX/drive_c/windows/system32/d3d11.dll\" \"$GAME_DIR/dxvk.dll\""
echo "  rm -rf \"$GAME_DIR/enbcache\""
echo "Do this refresh any time you change Skyrim's compatibility tool version"
echo "in Steam, including if you ever go back to GE-Proton Latest."
echo
echo "--- STEP H: Verify ---"
echo "1. Launch Skyrim Special Edition (see step 31 for the SKSE launch option)"
echo "2. First launch after installing/updating the preset, d3d11.dll, or"
echo "   switching Proton version will show 'ENBSeries compiling shaders,"
echo "   please wait' — this is normal, not an error, and can take anywhere"
echo "   from seconds to a couple minutes. It's safe to stop the game if"
echo "   it's interrupted; nothing is corrupted, it just recompiles on the"
echo "   next launch. The result is cached in $GAME_DIR/enbcache/ — delete"
echo "   that folder any time you update the preset, the ENB binary, or the"
echo "   Proton version, so you get a clean recompile instead of a stale one:"
echo "     rm -rf \"$GAME_DIR/enbcache\""
echo "3. Once loaded, you should see the ENB logo flash briefly top-left,"
echo "   Shift+Enter should open the ENBSeries in-game editor overlay, and"
echo "   colors/lighting should look visibly different from vanilla"
echo "4. Check $GAME_DIR/enblog.txt if ENB fails to initialize"
echo

echo "33-skyrim-enb complete"
